import {TYPES,score,safeTypes,resultLink,savedResult,normalizeSaved,catalog} from './core.mjs';
import {copy,questions,profiles} from './data.mjs?v=20260928-copy3';
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nl=s=>esc(s).replace(/\n/g,'<br>');
const keys={fav:'usmori-play-favorites-v1',results:'usmori-play-results-v1'};
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
const query=new URL(location.href).searchParams;
let lang=query.get('lang')==='ja'?'ja':'ko', shared=safeTypes(query.get('result')), view=shared.length?'shared':query.get('test')==='recharge'?'intro':'home', category='all', answers=Array(8).fill(null), step=0, ownResult=null;
let fav=read(keys.fav,[]);fav=Array.isArray(fav)?fav.filter(id=>catalog.some(q=>q.id===id)):[];
let saved=normalizeSaved(read(keys.results,[]));
let toastTimer;
const icons={
home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',
heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
spark:'<path d="m12 3 2.6 6.4L21 12l-6.4 2.6L12 21l-2.6-6.4L3 12l6.4-2.6z"/>',
book:'<path d="M4 3h13a3 3 0 0 1 3 3v15H6a3 3 0 0 1-3-3V4a1 1 0 0 1 1-1Zm0 13h16M7 7h8m-8 4h5"/>',
arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',
back:'<path d="M19 12H5m5-5-5 5 5 5"/>',
share:'<path d="M12 16V3m-5 5 5-5 5 5M5 13v7h14v-7"/>',
battery:'<rect x="2" y="7" width="18" height="10" rx="3"/><path d="M23 10v4M6 10v4m4-4v4m4-4v4"/>',
check:'<path d="m5 12 4 4L19 6"/>',
trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>',
clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'
};
const icon=(n,cls='')=>'<svg class="icon '+cls+'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(icons[n]||icons.spark)+'</svg>';
const t=()=>copy[lang];
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3300)}
function urlReset(){const u=new URL(location.href);u.search='';u.searchParams.set('lang',lang);if(view==='intro'||view==='quiz')u.searchParams.set('test','recharge');if(view==='shared')u.searchParams.set('result',shared.join(','));history.replaceState(null,'',u)}
function go(v){view=v;if(v!=='shared')shared=[];urlReset();render();window.scrollTo({top:0,behavior:'instant'});$('#main').focus({preventScroll:true})}
function art(name,alt='',cls=''){return '<img class="'+cls+'" src="./assets/'+name+'.webp" alt="'+esc(alt)+'" width="1536" height="1024" decoding="async">'}
function quizCard(){const q=catalog[0],isFav=fav.includes(q.id);return '<article class="quiz-card"><div class="card-art"><button class="image-link" data-action="intro" aria-label="'+esc(t().start)+'">'+art('hug',q.title[lang])+'</button><span class="tag new-tag">'+(lang==='ko'?'NEW · 위로 편':'NEW · いたわり編')+'</span><button class="heart-button '+(isFav?'selected':'')+'" data-action="favorite" aria-pressed="'+isFav+'" aria-label="'+esc(isFav?t().unheart:t().heart)+'">'+icon('heart')+'</button></div><div class="card-copy"><p class="eyebrow">'+t().featured+'</p><h3>'+nl(q.title[lang])+'</h3><p>'+nl(q.description[lang])+'</p><div class="card-tail"><span class="metadata">'+icon('clock')+t().minutes+'</span><button class="round-arrow" data-action="intro" aria-label="'+esc(t().start)+'">'+icon('arrow')+'</button></div></div></article>'}
function empty(title,body){return '<section class="empty-state">'+art('quiet','', 'empty-art')+'<h2>'+esc(title)+'</h2><p>'+esc(body)+'</p><button class="button primary" data-action="home">'+t().explore+icon('arrow')+'</button></section>'}
function home(){return '<section class="welcome"><div class="welcome-copy"><span class="tag">'+icon('spark')+t().tag+'</span><h1>'+nl(t().greeting)+'</h1><p>'+nl(t().welcome)+'</p><button class="button primary" data-action="intro">'+t().start+icon('arrow')+'</button><span class="hero-foot">'+icon('battery')+t().minutes+'</span></div><div class="welcome-art">'+art('hero',lang==='ko'?'작은 놀이방에서 마음 카드를 고르는 수달 두 마리':'小さなあそび部屋で心のカードを選ぶ2匹のラッコ')+'<span class="floating-note">'+(lang==='ko'?'오늘의 마음도, 소중히 ♡':'今日の気持ちも、大切に ♡')+'</span></div></section><section class="library"><div class="section-heading"><div><p class="eyebrow">A LITTLE PLAY, A LITTLE CLOSER</p><h2>'+t().library+'</h2></div><span class="subtle">'+t().one+'</span></div><div class="chips" role="group" aria-label="'+t().all+'">'+['all','comfort','conversation','daily'].map(c=>'<button class="chip '+(category===c?'active':'')+'" data-category="'+c+'" aria-pressed="'+(category===c)+'">'+esc(t()[c])+'</button>').join('')+'</div>'+(category==='all'||category==='comfort'?'<div class="card-grid">'+quizCard()+'<aside class="letter-card"><div class="letter-stamp">'+icon('heart')+'</div><p class="eyebrow">'+(lang==='ko'?'수달의 작은 편지':'ラッコからのお手紙')+'</p><h3>'+t().soon+'</h3><p>'+t().soonBody+'</p><div class="stitched-heart">♡</div><span class="signature">with love, Usmori</span></aside></div>':empty(t().emptyCategory,t().soonBody))+'</section>'}
function intro(){return '<section class="intro-panel"><button class="text-button back-button" data-action="home">'+icon('back')+t().home+'</button><div class="intro-layout"><div class="intro-art">'+art('hug',catalog[0].title[lang])+'<span class="tag">'+t().featured+'</span></div><div class="intro-copy"><span class="pill">'+icon('battery')+t().minutes+'</span><h1>'+nl(catalog[0].title[lang])+'</h1><p class="lead">'+nl(t().intro)+'</p><p>'+t().introBody+'</p><button class="button primary wide" data-action="begin">'+t().begin+icon('arrow')+'</button><p class="fine">'+t().disclaimer+'</p></div></div></section>'}
function quiz(){const q=questions[step];const order=TYPES.map((_,i)=>TYPES[(i+step)%4]);return '<section class="question-panel"><div class="question-top"><button class="text-button" data-action="previous">'+icon('back')+t().back+'</button><span class="count"><strong>'+String(step+1).padStart(2,'0')+'</strong> / 08</span><img src="../usmori-avatar.jpg" alt="" width="42" height="42"></div><div class="progress" role="progressbar" aria-valuenow="'+(step+1)+'" aria-valuemin="0" aria-valuemax="8" aria-label="'+t().question+'">'+questions.map((_,i)=>'<span class="'+(i<=step?'filled':'')+'"></span>').join('')+'</div><p class="eyebrow question-eyebrow">'+t().progress+'</p><h1 tabindex="-1" id="question-title">'+nl(q[lang])+'</h1><div class="answers" role="radiogroup" aria-labelledby="question-title">'+order.map((type,i)=>'<button class="answer '+(answers[step]===type?'chosen':'')+'" role="radio" aria-checked="'+(answers[step]===type)+'" data-answer="'+type+'"><span class="answer-letter">'+(i+1)+'</span><span>'+esc(q[lang+'A'][TYPES.indexOf(type)])+'</span><span class="answer-check">'+(answers[step]===type?icon('check'):'')+'</span></button>').join('')+'</div><button class="button primary wide next" data-action="next" '+(!answers[step]?'disabled':'')+'>'+(step===7?t().finish:t().next)+icon('arrow')+'</button><p class="fine center">'+t().keepGoing+'</p></section>'}
function result(){const types=view==='shared'?shared:ownResult?.types;if(!types?.length)return intro();const mixed=types.length>1,isShared=view==='shared';const lead=profiles[types[0]][lang];return '<section class="result-panel">'+(isShared?'<div class="shared-notice"><strong>'+t().shared+'</strong><p>'+t().sharedBody+'</p></div>':'')+'<div class="result-hero">'+art(mixed?'hero':profiles[types[0]].image,'')+'<span class="tag">'+t().resultLabel+'</span></div><div class="result-heading"><span class="result-spark">'+icon(mixed?'spark':'battery')+'</span><h1>'+nl(mixed?t().mixed:lead.name)+'</h1><p class="lead">'+esc(mixed?t().mixedBody:lead.short)+'</p></div><div class="profile-list">'+types.map(type=>{const p=profiles[type][lang];return '<article class="profile-detail '+type+'">'+(mixed?'<div class="mini-profile">'+art(profiles[type].image,'')+'<h2>'+esc(p.name)+'</h2></div>':'')+'<h3 class="profile-about">'+t().about+'</h3><p class="profile-description">'+esc(p.body)+'</p><div class="request-card"><span>'+icon('heart')+t().tips+'</span><blockquote>'+esc(p.request)+'</blockquote></div><h3>'+t().try+'</h3><ul class="tip-list">'+p.tips.map(v=>'<li>'+icon('spark')+'<span>'+esc(v)+'</span></li>').join('')+'</ul></article>'}).join('')+'</div><div class="result-actions">'+(isShared?'<button class="button primary wide" data-action="begin">'+t().mine+icon('arrow')+'</button>':'<button class="button primary wide" data-action="share">'+icon('share')+t().share+'</button><button class="button secondary wide" data-action="save">'+icon('book')+t().save+'</button>')+(!isShared?'<button class="text-button" data-action="copy">'+icon('share')+t().copy+'</button>':'')+'<div id="share-fallback"></div><button class="text-button" data-action="begin">'+t().retry+'</button><button class="text-button" data-action="home">'+t().explore+'</button></div><p class="fine center result-disclaimer">'+t().disclaimer+'</p></section>'}
function savedView(){return '<section class="saved-page"><p class="eyebrow">MY LITTLE COLLECTION</p><h1>'+t().results+'</h1><p class="subtle">'+t().local+'</p>'+(saved.length?'<div class="saved-grid">'+saved.map((r,i)=>'<article class="saved-card">'+art(r.types.length>1?'hero':profiles[r.types[0]].image,'')+'<div><time>'+esc(new Date(r.date).toLocaleDateString(lang==='ja'?'ja-JP':'ko-KR'))+'</time><h2>'+esc(r.types.length>1?t().mixed.replace('\n',' '):profiles[r.types[0]][lang].name)+'</h2><button class="button secondary" data-open="'+i+'">'+t().finish+icon('arrow')+'</button><button class="text-button delete" data-delete="'+i+'">'+icon('trash')+t().remove+'</button></div></article>').join('')+'</div>':empty(t().noneSaved,t().noneSavedBody))+'</section>'}
function render(){document.documentElement.lang=lang;document.title=t().room+' · Usmori';$('#brand-sub').textContent=t().room;document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===lang)));let content=view==='home'?home():view==='favorites'?'<section class="saved-page"><p class="eyebrow">SAVED WITH LOVE</p><h1>'+t().favorites+'</h1>'+(fav.length?'<div class="favorite-grid">'+quizCard()+'</div>':empty(t().noneFav,t().noneFavBody))+'</section>':view==='results'?savedView():view==='intro'?intro():view==='quiz'?quiz():result();$('#main').innerHTML=content;
$('#footer').innerHTML='<p class="footer-love">♡ '+t().made+'</p><p>'+t().private+'</p><p>'+t().art+'</p><div><a href="../index.html">'+t().source+'</a><a href="../privacy.html#'+lang+'">'+(lang==='ko'?'개인정보처리방침':'プライバシー')+'</a><a href="../support.html#'+lang+'">'+(lang==='ko'?'도움말':'サポート')+'</a></div><small>Usmori · Otterday Studio</small>';
$('#bottom-nav').innerHTML=[['home','home'],['favorites','heart'],['results','book']].map(([v,i])=>'<button data-action="'+v+'" class="'+(view===v?'active':'')+'" '+(view===v?'aria-current="page"':'')+'>'+icon(i)+'<span>'+t()[v]+'</span></button>').join('');
}
async function copyLink(){const types=ownResult?.types;if(!types?.length)return;const url=resultLink(location.href,lang,types);$('#share-fallback').innerHTML='<label class="copy-fallback">'+t().copyHelp+'<input readonly aria-label="Result link" value="'+esc(url)+'"></label>';try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(url);toast(t().copied)}}catch{}}
async function share(){const types=ownResult?.types;if(!types?.length)return;const url=resultLink(location.href,lang,types),title=t().shareTitle;try{if(navigator.share){await navigator.share({title,text:types.map(k=>profiles[k][lang].name).join(' · '),url});return}if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(url);toast(t().copied);return}}catch(e){if(e.name==='AbortError')return}
$('#share-fallback').innerHTML='<label class="copy-fallback">'+t().copyHelp+'<input readonly aria-label="Result link" value="'+esc(url)+'"></label>'}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.lang){lang=b.dataset.lang;urlReset();render();return}if(b.dataset.category){category=b.dataset.category;render();return}if(b.dataset.answer){answers[step]=b.dataset.answer;const a=b.dataset.answer;render();$('[data-answer="'+a+'"]').focus({preventScroll:true});return}
if(b.dataset.delete!==undefined){saved.splice(Number(b.dataset.delete),1);if(!write(keys.results,saved)){toast(t().saveFail);return}render();toast(t().removed);return}
if(b.dataset.open!==undefined){ownResult={types:saved[Number(b.dataset.open)].types};go('result');return}
const a=b.dataset.action;if(['home','favorites','results','intro'].includes(a)){go(a);return}if(a==='favorite'){const id=catalog[0].id;const next=fav.includes(id)?fav.filter(x=>x!==id):[...fav,id];if(write(keys.fav,next)){fav=next;render()}else toast(t().saveFail);return}if(a==='begin'){answers=Array(8).fill(null);step=0;ownResult=null;go('quiz');return}if(a==='previous'){if(step===0){go('intro')}else{step--;render();$('#question-title').focus();window.scrollTo({top:0,behavior:'instant'})}return}if(a==='next'){if(!answers[step])return;if(step<7){step++;render();$('#question-title').focus();window.scrollTo({top:0,behavior:'instant'})}else{ownResult=score(answers);go('result')}return}if(a==='copy'){copyLink();return}if(a==='share'){share();return}if(a==='save'&&ownResult){const entry=savedResult(ownResult.types,lang),next=[entry,...saved].slice(0,20);if(write(keys.results,next)){saved=next;toast(t().saved)}else toast(t().saveFail)}});
document.addEventListener('keydown',e=>{if(!e.target.matches('[role="radio"]')||!['ArrowDown','ArrowUp','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const buttons=[...document.querySelectorAll('[role="radio"]')],idx=buttons.indexOf(e.target),delta=['ArrowDown','ArrowRight'].includes(e.key)?1:-1;buttons[(idx+delta+buttons.length)%buttons.length].focus()});
render();
