import test from 'node:test';import assert from 'node:assert/strict';
import {catalog,CONVERSATION_TYPES,score,resultLink,savedResult,normalizeSaved,safeTypes} from './core.mjs';
import {questions,profiles,copy} from './conversation.mjs';
test('Second quiz contains eight distinct complete prompts in KO JA EN',()=>{assert.equal(questions.length,8);for(const lang of ['ko','ja','en']){assert.equal(new Set(questions.map(q=>q[lang])).size,8);for(const q of questions){assert.ok(q[lang].length>10);assert.equal(q[lang+'A'].length,4);assert.equal(new Set(q[lang+'A']).size,4)}for(const type of CONVERSATION_TYPES){const p=profiles[type][lang];for(const k of ['name','short','body','request'])assert.ok(p[k].length>5);assert.equal(p.tips.length,3)}assert.deepEqual(Object.keys(copy[lang]).sort(),Object.keys(copy.ko).sort())}});
test('Every conversation type wins on a full matching answer set',()=>{for(const type of CONVERSATION_TYPES)assert.deepEqual(score(Array(8).fill(type),'conversation-02').types,[type]);assert.deepEqual(score([...CONVERSATION_TYPES,...CONVERSATION_TYPES],'conversation-02').types,CONVERSATION_TYPES)});
test('Answers and result types from another quiz are rejected',()=>{assert.throws(()=>score(Array(8).fill('hug'),'conversation-02'));assert.throws(()=>score(Array(8).fill('pause'),'recharge-01'));assert.deepEqual(safeTypes('hug,pause,pause,evil','conversation-02'),['pause'])});
test('Share URL keeps only locale, quiz and allowed result; no answers',()=>{const u=new URL(resultLink('https://usmori.pages.dev/recharge/?answers=private&name=secret#bad','ja',['pause','hug'],'conversation-02'));assert.equal(u.search,'?lang=ja&test=conversation&result=pause');assert.equal(u.hash,'')});
test('Old and new saved results survive together with isolated types and minimal data',()=>{const old=savedResult(['hug'],'ko','2026-09-28T00:00:00Z');const next=savedResult(['write'],'en','2026-09-30T00:00:00Z','conversation-02');assert.deepEqual(normalizeSaved([old,{...next,answers:['secret']}]),[old,next]);assert.deepEqual(normalizeSaved([{...next,types:['hug']},{...next,quiz:'unknown'}]),[])});
test('Catalog lists only playable complete quizzes and unique IDs',()=>{assert.equal(catalog.length,2);assert.equal(new Set(catalog.map(q=>q.id)).size,2);for(const q of catalog){assert.equal(q.questions,8);for(const lang of ['ko','ja','en'])assert.ok(q.title[lang]&&q.description[lang])}});
