import test from 'node:test';import assert from 'node:assert/strict';import {score,TYPES,safeTypes,savedResult,normalizeSaved,resultLink,catalog} from './core.mjs';import {questions,profiles,copy} from './data.mjs';
test('Every available quiz has eight complete localized questions',()=>{assert.equal(catalog.length,1);assert.equal(questions.length,8);for(const q of questions)for(const lang of ['ko','ja','en']){assert.ok(q[lang].length>5);assert.equal(q[lang+'A'].length,4);assert.ok(q[lang+'A'].every(x=>typeof x==='string'&&x.length>3))}});
for(const type of TYPES)test('Dominant '+type+' has complete warm result',()=>{assert.deepEqual(score(Array(8).fill(type)).types,[type]);for(const lang of ['ko','ja','en']){assert.equal(profiles[type][lang].tips.length,3);assert.ok(profiles[type][lang].request)}});
test('Ties preserve all co-leading types',()=>{assert.deepEqual(score(['hug','hug','hug','listen','listen','listen','quiet','solve']).types,['listen','hug']);assert.deepEqual(score([...TYPES,...TYPES]).types,TYPES)});
test('Incomplete, sparse and invalid inputs cannot create a result',()=>{for(const a of [[],Array(8),Array(7).fill('hug'),Array(9).fill('hug'),[...Array(7).fill('hug'),null],[...Array(7).fill('hug'),'evil']])assert.throws(()=>score(a))});
test('Shared links contain only safe locale and selected result types',()=>{const u=new URL(resultLink('https://example.com/usmori-support/recharge/?secret=bad&answers=private#x','ja',['hug','oops','hug']));assert.equal(u.pathname,'/usmori-support/recharge/');assert.equal(u.search,'?lang=ja&result=hug');assert.equal(u.hash,'');assert.deepEqual(safeTypes('<script>,quiet,quiet'),['quiet'])});
test('Saved results minimize fields and tolerate corrupt storage',()=>{const value=savedResult(['quiet'],'ko','2026-09-28T09:00:00Z');assert.deepEqual(Object.keys(value).sort(),['date','lang','quiz','types']);assert.deepEqual(normalizeSaved([{},null,{...value,types:'bad'},{...value,date:'bad'}]),[]);const clean=normalizeSaved([{...value,answers:['secret'],name:'private'}]);assert.deepEqual(clean,[value]);assert.deepEqual(normalizeSaved({}),[])});
test('Both locale dictionaries cover same UI keys',()=>assert.deepEqual(Object.keys(copy.ko).sort(),Object.keys(copy.ja).sort()));

test('English UI dictionary is complete',()=>assert.deepEqual(Object.keys(copy.en).sort(),Object.keys(copy.ko).sort()));
test('English survives saved and shared results without extra data',()=>{assert.equal(new URL(resultLink('https://example.com/?answers=secret','en',['hug'])).search,'?lang=en&result=hug');assert.equal(normalizeSaved([savedResult(['quiet'],'en')])[0].lang,'en');assert.equal(savedResult(['quiet'],'xx').lang,'ko');assert.ok(catalog[0].title.en);});
